SSST/Models/Siswa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SSST.Models
{
    public class Siswa
    {
        public int SiswaID { get; set; }

        [Display(Name ="Nomor Induk Siswa"), StringLength(12)]
        public string SiswaNim { get; set; }

        [Display(Name ="Nama Siswa")]
        public string SiswaNama { get; set; }
        [Display(Name ="Alamat")]
        public string SiswaAlamat { get; set; }
        //penunjuk anggota pada kelas
        [Display(Name ="Kelas")]

        //single key, satu siswa -> satu kelas

        public int? KelasID { get; set; }
        public virtual Kelas Kelas { get; set; }

        public List<SiswaNilai> SiswaNilais { get; set; }

    }
}

SSST/Controllers/SiswaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using SSST.Data;
using SSST.Models;

namespace SSST.Controllers
{
    public class SiswaController : Controller
    {
        private readonly SSSTContext _context;

        public SiswaController(SSSTContext context)
        {
            _context = context;
        }

        // GET: Siswa
        public async Task<IActionResult> Index()
        {
            var sSSTContext = _context.Siswa.Include(s => s.Kelas);
            return View(await sSSTContext.ToListAsync());
        }

        // GET: Siswa/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var siswa = await _context.Siswa
                .Include(s => s.Kelas)
                .FirstOrDefaultAsync(m => m.SiswaID == id);
            if (siswa == null)
            {
                return NotFound();
            }

            return View(siswa);
        }

        // GET: Siswa/InputNilaiSiswa/5
        public async Task<IActionResult> InputNilaiSiswa(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var siswa = await _context.Siswa
                .Include(s => s.Kelas)
                .FirstOrDefaultAsync(m => m.SiswaID == id);
            if (siswa == null)
            {
                return NotFound();
            }
            var listMapel = _context.MataPelajaran.Where(mp => mp.KelasID == siswa.KelasID).ToList();

            foreach (var pl in listMapel)
            {
                bool ada = _context.SiswaNilai.Any(ss => ss.SiswaID == siswa.SiswaID && ss.MapelID == pl.MapelID);
                if (!ada)
                {
                     SiswaNilai sm = new SiswaNilai { Siswa = siswa, MataPelajaran = pl };
                    _context.Add(sm);
                    _context.SaveChanges();
                }

            }

            var snl = _context.SiswaNilai.Where(s => s.SiswaID == id)
                .Include(s => s.Siswa)
                .Include(m => m.MataPelajaran);
            ViewBag.idkelas = siswa.KelasID;
            return View(snl.ToList());
        }

        // POST: Siswa/InputNilaiSiswa/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InputNilaiSiswa(int id,[Bind("SiswaID,MapelID,NilaiKKM,Nilai")] List<SiswaNilai> snl)
        {
            var idkelas = _context.Siswa.Find(id).KelasID;
            if (ModelState.IsValid)
            {
                foreach (var item in snl)
                {
                    _context.Update(item);
                    _context.SaveChanges();

                }

                return RedirectToAction("DaftarSiswaKelas","Kelas", new { id = idkelas });
            }

            return View(snl);
        }

        // GET: Siswa/LihatNilaiSiswa/5
        public async Task<IActionResult> LihatNilaiSiswa(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var siswa = await _context.Siswa
                .Include(s => s.Kelas)
                .FirstOrDefaultAsync(m => m.SiswaID == id);
            if (siswa == null)
            {
                return NotFound();
            }
            var listMapel = _context.MataPelajaran.Where(mp => mp.KelasID == siswa.KelasID).ToList();

            foreach (var pl in listMapel)
            {
                bool ada = _context.SiswaNilai.Any(ss => ss.SiswaID == siswa.SiswaID && ss.MapelID == pl.MapelID);
                if (!ada)
                {
                    SiswaNilai sm = new SiswaNilai { Siswa = siswa, MataPelajaran = pl };
                    _context.Add(sm);
                    _context.SaveChanges();
                }

            }

            var snl = _context.SiswaNilai.Where(s => s.SiswaID == id)
                .Include(s => s.Siswa)
                .Include(m => m.MataPelajaran);
            ViewBag.idkelas = siswa.KelasID;
            return View(snl.ToList());
        }
        // GET: Siswa/Create
        public IActionResult Create()
        {
            ViewData["KelasID"] = new SelectList(_context.Kelas, "KelasID", "KelasNama");
            return View();
        }

        // POST: Siswa/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SiswaID,SiswaNim,SiswaNama,SiswaAlamat,KelasID")] Siswa siswa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(siswa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["KelasID"] = new SelectList(_context.Kelas, "KelasID", "KelasNama", siswa.KelasID);
            return View(siswa);
        }

        // GET: Siswa/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var siswa = await _context.Siswa.FindAsync(id);
            if (siswa == null)
            {
                return NotFound();
            }
            ViewData["KelasID"] = new SelectList(_context.Kelas, "KelasID", "KelasNama", siswa.KelasID);
            return View(siswa);
        }

        // POST: Siswa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SiswaID,SiswaNim,SiswaNama,SiswaAlamat,KelasID")] Siswa siswa)
        {
            if (id != siswa.SiswaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(siswa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SiswaExists(siswa.SiswaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KelasID"] = new SelectList(_context.Kelas, "KelasID", "KelasNama", siswa.KelasID);
            return View(siswa);
        }

        // GET: Siswa/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var siswa = await _context.Siswa
                .Include(s => s.Kelas)
                .FirstOrDefaultAsync(m => m.SiswaID == id);
            if (siswa == null)
            {
                return NotFound();
            }

            return View(siswa);
        }

        // POST: Siswa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var siswa = await _context.Siswa.FindAsync(id);
            _context.Siswa.Remove(siswa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SiswaExists(int id)
        {
            return _context.Siswa.Any(e => e.SiswaID == id);
        }
    }
}

SSST/Views/Siswa/Create.cshtml
@model SSST.Models.Siswa

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Siswa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SiswaNim" class="control-label"></label>
                <input asp-for="SiswaNim" class="form-control" />
                <span asp-validation-for="SiswaNim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SiswaNama" class="control-label"></label>
                <input asp-for="SiswaNama" class="form-control" />
                <span asp-validation-for="SiswaNama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SiswaAlamat" class="control-label"></label>
                <input asp-for="SiswaAlamat" class="form-control" />
                <span asp-validation-for="SiswaAlamat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KelasID" class="control-label"></label>
                <select asp-for="KelasID" class ="form-control" asp-items="ViewBag.KelasID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SSST/Views/Siswa/Delete.cshtml
@model SSST.Models.Siswa

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Siswa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiswaNim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SiswaNim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiswaNama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SiswaNama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiswaAlamat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SiswaAlamat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kelas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kelas.KelasID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SiswaID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SSST/Views/Siswa/Details.cshtml
@model SSST.Models.Siswa

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Siswa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiswaNim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SiswaNim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiswaNama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SiswaNama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiswaAlamat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SiswaAlamat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kelas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kelas.KelasID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SiswaID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SSST/Views/Siswa/Edit.cshtml
@model SSST.Models.Siswa

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Siswa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SiswaID" />
            <div class="form-group">
                <label asp-for="SiswaNim" class="control-label"></label>
                <input asp-for="SiswaNim" class="form-control" />
                <span asp-validation-for="SiswaNim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SiswaNama" class="control-label"></label>
                <input asp-for="SiswaNama" class="form-control" />
                <span asp-validation-for="SiswaNama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SiswaAlamat" class="control-label"></label>
                <input asp-for="SiswaAlamat" class="form-control" />
                <span asp-validation-for="SiswaAlamat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KelasID" class="control-label"></label>
                <select asp-for="KelasID" class="form-control" asp-items="ViewBag.KelasID"></select>
                <span asp-validation-for="KelasID" class="text-danger"></span>
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SSST/Views/Siswa/Index.cshtml
@model IEnumerable<SSST.Models.Siswa>

@{
    ViewData["Title"] = "Daftar Siswa";
}

<h1>Daftar Siswa</h1>

<p>
    <a asp-action="Create">Daftar Baru</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SiswaNim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SiswaNama)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SiswaAlamat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kelas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SiswaNim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SiswaNama)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SiswaAlamat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kelas.KelasNama)
            </td>
            <td>
                <a asp-action="InputNilaiSiswa" asp-route-id="@item.SiswaID">Input Nilai Siswa</a> |
                <a asp-action="LihatNilaiSiswa" asp-route-id="@item.SiswaID">Lihat Nilai Siswa</a> |
                <a asp-action="Edit" asp-route-id="@item.SiswaID">Ubah Data</a> |
                <a asp-action="Details" asp-route-id="@item.SiswaID">Detil</a> |
                <a asp-action="Delete" asp-route-id="@item.SiswaID">Hapus</a> |
            </td>
        </tr>
}
    </tbody>
</table>

SSST/Views/Siswa/InputNilaiSiswa.cshtml
@model List<SSST.Models.SiswaNilai>

@{
    ViewData["Title"] = "Input Nilai";
}

<h1>Input Nilai Siswa</h1>
<h4>Nama: @Model.First().Siswa.SiswaNama</h4>
<h4>NIM : @Model.First().Siswa.SiswaNim</h4>
<hr />
@using (Html.BeginForm("InputNilaiSiswa", "Siswa", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table style="width:100%" border="1">
        <thead>
            <tr>
                <th>Mata Pelajaran</th>
                <th>Nilai KKM</th>
                <th>Nilai Mata Pelajaran</th>
            </tr>
        </thead>
        <tbody>
            @for (int item = 0; item < Model.Count; item++)
            {
                <tr>
                    <input asp-for="@Model[item].MapelID" hidden />
                    <input asp-for="@Model[item].SiswaID" hidden />
                    <td>@Model[item].MataPelajaran.MapelNama</td>
                    <td><input asp-for="@Model[item].NilaiKKM" max="100" min="0" maxlength="3"/></td>
                    <td><input asp-for="@Model[item].Nilai" max="100" min="0" maxlength="3"/></td>
                </tr>
            }
        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
}


<div>
    <a asp-controller="Kelas" asp-action="DaftarSiswaKelas" asp-route-id="@ViewBag.idkelas">Kembali ke Kelas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SSST/Views/Siswa/LihatNilaiSiswa.cshtml
@model List<SSST.Models.SiswaNilai>

@{
    ViewData["Title"] = "Lihat Nilai";
}

<h1>Input Nilai Siswa</h1>

<h4>Nama: @Model.First().Siswa.SiswaNama</h4>
<h4>NIM : @Model.First().Siswa.SiswaNim</h4>
<hr />

<table style="width:100%" border="1">
    <thead>
        <tr>
            <th>Mata Pelajaran</th>
            <th>Nilai KKM</th>
            <th>Nilai Mata Pelajaran</th>
        </tr>
    </thead>
    <tbody>
        @for (int item = 0; item < Model.Count; item ++)
        {
            <tr>
                <input type="hidden" asp-for="@Model[item].SiswaID" />
                <input type="hidden" asp-for="@Model[item].MapelID" />
                <td>@Model[item].MataPelajaran.MapelNama</td>
                <td>@Html.DisplayFor(m => m[item].NilaiKKM)</td>
                <td>@Html.DisplayFor(m => m[item].Nilai)</td>
            </tr>
        }
    </tbody>
</table>



<div>
    <a asp-controller="Kelas" asp-action="DaftarSiswaKelas" asp-route-id="@ViewBag.idkelas">Kembali ke Kelas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}