SSST/Models/MataPelajaran.cs
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;

namespace SSST.Models
{
    public class MataPelajaran
    {
       
        [Key]
        public int MapelID { get; set; }

        [Display(Name ="Nama Pelajaran")]
        public string MapelNama { get; set; }

        [Display(Name ="Keterangan")]
        public string MapelDesc { get; set; }
        [Display(Name ="Tingkat")]
        public Tingkat MapelGrade { get; set; }

        //untuk menunjuk guru pengampu
        [Display(Name ="Guru Pengampu")]
        public int GuruID { get; set; }
        public virtual Guru Guru { get; set; }

        //untuk menghubungkan kelas
        public int KelasID { get; set; }
        public virtual Kelas Kelas { get; set; }

        public List<SiswaNilai> SiswaNilais { get; set; }


    }
    public enum Tingkat
    {
        I,
        II,
        III,
        IV,
        V,
        VI,
        VII,
        VIII,
        IX,
        X,
        XI,
        XII
    }
}

SSST/Controllers/MataPelajaranController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SSST.Data;
using SSST.Models;

namespace SSST.Controllers
{
    public class MataPelajaranController : Controller
    {
        private readonly SSSTContext _context;

        public MataPelajaranController(SSSTContext context)
        {
            _context = context;
        }

        // GET: MataPelajaran
        public async Task<IActionResult> Index()
        {
            var sSSTContext = _context.MataPelajaran.Include(m => m.Guru).Include(m => m.Kelas);
            return View(await sSSTContext.ToListAsync());
        }

        // GET: MataPelajaran/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mataPelajaran = await _context.MataPelajaran
                .Include(m => m.Guru)
                .Include(m => m.Kelas)
                .FirstOrDefaultAsync(m => m.MapelID == id);
            if (mataPelajaran == null)
            {
                return NotFound();
            }

            return View(mataPelajaran);
        }

        // GET: MataPelajaran/Create
        public IActionResult Create()
        {
            ViewData["GuruID"] = new SelectList(_context.Guru, "GuruID", "GuruNama");
            ViewData["KelasID"] = new SelectList(_context.Kelas, "KelasID", "KelasNama");
            return View();
        }

        // POST: MataPelajaran/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MapelID,MapelNama,MapelDesc,MapelGrade,GuruID,KelasID")] MataPelajaran mataPelajaran)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mataPelajaran);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GuruID"] = new SelectList(_context.Guru, "GuruID", "GuruNama", mataPelajaran.GuruID);
            ViewData["KelasID"] = new SelectList(_context.Kelas, "KelasID", "KelasNama", mataPelajaran.KelasID);
            return View(mataPelajaran);
        }

        // GET: MataPelajaran/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mataPelajaran = await _context.MataPelajaran.FindAsync(id);
            if (mataPelajaran == null)
            {
                return NotFound();
            }
            ViewData["GuruID"] = new SelectList(_context.Guru, "GuruID", "GuruNama", mataPelajaran.GuruID);
            ViewData["KelasID"] = new SelectList(_context.Kelas, "KelasID", "KelasNama", mataPelajaran.KelasID);
            return View(mataPelajaran);
        }

        // POST: MataPelajaran/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MapelID,MapelNama,MapelDesc,MapelGrade,GuruID,KelasID")] MataPelajaran mataPelajaran)
        {
            if (id != mataPelajaran.MapelID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mataPelajaran);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MataPelajaranExists(mataPelajaran.MapelID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GuruID"] = new SelectList(_context.Guru, "GuruID", "GuruNama", mataPelajaran.GuruID);
            ViewData["KelasID"] = new SelectList(_context.Kelas, "KelasID", "KelasNama", mataPelajaran.KelasID);
            return View(mataPelajaran);
        }

        // GET: MataPelajaran/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mataPelajaran = await _context.MataPelajaran
                .Include(m => m.Guru)
                .Include(m => m.Kelas)
                .FirstOrDefaultAsync(m => m.MapelID == id);
            if (mataPelajaran == null)
            {
                return NotFound();
            }

            return View(mataPelajaran);
        }
        // GET: MataPelajaran/LihatNilaiSiswa/5
        //id = MapelID
        public async Task<IActionResult> LihatNilaiSiswa(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mapel = await _context.MataPelajaran
                .Include(s => s.Kelas)
                .FirstOrDefaultAsync(m => m.MapelID == id);

            if (mapel == null)
            {
                return NotFound();
            }

            var snl = _context.SiswaNilai.Where(s => s.MapelID == id)
                .Include(s => s.Siswa)
                .Include(m => m.MataPelajaran);
            return View(snl.ToList());
        }

        // POST: MataPelajaran/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mataPelajaran = await _context.MataPelajaran.FindAsync(id);
            _context.MataPelajaran.Remove(mataPelajaran);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MataPelajaranExists(int id)
        {
            return _context.MataPelajaran.Any(e => e.MapelID == id);
        }
    }
}

SSST/Views/MataPelajaran/Create.cshtml
@model SSST.Models.MataPelajaran

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MataPelajaran</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MapelNama" class="control-label"></label>
                <input asp-for="MapelNama" class="form-control" />
                <span asp-validation-for="MapelNama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapelDesc" class="control-label"></label>
                <input asp-for="MapelDesc" class="form-control" />
                <span asp-validation-for="MapelDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapelGrade" class="control-label"></label>
                <select asp-for="MapelGrade" class="form-control" asp-items="Html.GetEnumSelectList<Tingkat>()"></select>
                <span asp-validation-for="MapelGrade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuruID" class="control-label"></label>
                <select asp-for="GuruID" class ="form-control" asp-items="ViewBag.GuruID"></select>
            </div>
            <div class="form-group">
                <label asp-for="KelasID" class="control-label"></label>
                <select asp-for="KelasID" class ="form-control" asp-items="ViewBag.KelasID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SSST/Views/MataPelajaran/Delete.cshtml
@model SSST.Models.MataPelajaran

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MataPelajaran</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MapelNama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MapelNama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MapelDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MapelDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MapelGrade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MapelGrade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Guru)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Guru.GuruID)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kelas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kelas.KelasID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MapelID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SSST/Views/MataPelajaran/Details.cshtml
@model SSST.Models.MataPelajaran

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MataPelajaran</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MapelNama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MapelNama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MapelDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MapelDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MapelGrade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MapelGrade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Guru)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Guru.GuruID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kelas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kelas.KelasID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MapelID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SSST/Views/MataPelajaran/Edit.cshtml
@model SSST.Models.MataPelajaran

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MataPelajaran</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MapelID" />
            <div class="form-group">
                <label asp-for="MapelNama" class="control-label"></label>
                <input asp-for="MapelNama" class="form-control" />
                <span asp-validation-for="MapelNama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapelDesc" class="control-label"></label>
                <input asp-for="MapelDesc" class="form-control" />
                <span asp-validation-for="MapelDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MapelGrade" class="control-label"></label>
                <select asp-for="MapelGrade" class="form-control" asp-items="Html.GetEnumSelectList<Tingkat>()"></select>
                <span asp-validation-for="MapelGrade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuruID" class="control-label"></label>
                <select asp-for="GuruID" class="form-control" asp-items="ViewBag.GuruID"></select>
                <span asp-validation-for="GuruID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KelasID" class="control-label"></label>
                <select asp-for="KelasID" class="form-control" asp-items="ViewBag.KelasID"></select>
                <span asp-validation-for="KelasID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SSST/Views/MataPelajaran/Index.cshtml
@model IEnumerable<SSST.Models.MataPelajaran>

@{
    ViewData["Title"] = "Daftar Mata Pelajaran";
}

    <h1>Daftar Mata Pelajaran</h1>

<p>
    <a asp-action="Create">Buat Mata Pelajaran Baru</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MapelNama)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MapelDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MapelGrade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guru)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kelas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MapelNama)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MapelDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MapelGrade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Guru.GuruNama)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kelas.KelasNama)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MapelID">Edit</a> |
                <a asp-action="LihatNilaiSiswa" asp-route-id="@item.MapelID">Lihat Nilai Siswa</a> |
                <a asp-action="Delete" asp-route-id="@item.MapelID">Hapus</a>
            </td>
        </tr>
}
    </tbody>
</table>

SSST/Views/MataPelajaran/LihatNilaiSiswa.cshtml
@model List<SSST.Models.SiswaNilai>

@{
    ViewData["Title"] = "Lihat Nilai Per Mapel";
}

<h1>Daftar Nilai Siswa</h1>
<h4>Untuk Mata Pelajaran</h4>
<h4>@Model.First().MataPelajaran.MapelNama</h4>

<hr />
    <table style="width:100%" border="1">
        <thead>
            <tr>
                <th>Nama Siswa</th>
                <th>NIM</th>
                <th>Nilai</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.Siswa.SiswaNama</td>
                <td>@item.Siswa.SiswaNim</td>
                <td>@item.Nilai</td>
            </tr>
            }

        </tbody>
    </table>



<div>
    <a asp-controller="MataPelajaran" asp-action="Index">Kembali Daftar Pelajaran</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}